/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2023-11-20 02:57:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import java.sql.Timestamp;
import semi.review.*;

public final class reviewDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("semi.review");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.sql.Timestamp");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"./css/reviewDetail.css\">\r\n");
      out.write("	<title>가지고 싶은 물건, 가지가지 다~ 있다! 가지마켓</title>\r\n");
      out.write("	<script src=\"https://kit.fontawesome.com/def66b134a.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("	</head>\r\n");
      out.write("\r\n");
      out.write("	<body>\r\n");
      out.write("		<div class=\"wrap\">\r\n");
      out.write("	        <div class=\"inner\">\r\n");
      out.write("		        <div>\r\n");
      out.write("				");

			        if (session.getAttribute("USER_NAME") != null) {
			    
      out.write("\r\n");
      out.write("			        \r\n");
      out.write("			    ");
      out.write("\r\n");
      out.write("			    ");
 String user_name = (String)session.getAttribute("USER_NAME"); 
      out.write("\r\n");
      out.write("			    \r\n");
      out.write("			    <p class=\"sessionState\">");
      out.print( user_name );
      out.write("님 환영합니다! &nbsp;&nbsp;<a href=\"logout.jsp\">로그아웃</a></p>\r\n");
      out.write("			    ");

			        } else {
			    
      out.write("\r\n");
      out.write("				<p class=\"sessionState\"><a href=\"login.jsp\">로그인</a> &nbsp;&nbsp; <a href=\"register.jsp\">회원가입</a></p>\r\n");
      out.write("			    ");

			        }
			    
      out.write("\r\n");
      out.write("	                <header>\r\n");
      out.write("	                    <div class=\"logo\">\r\n");
      out.write("	                        <a href=\"mainpage.jsp\" style=\"text-decoration: none;\"><p class=\"gajimarket\">가지마켓</p></a>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                    <div class=\"mascot\">\r\n");
      out.write("	                        <a href=\"mainpage.jsp\"><img src=\"./img/gajidori.png\" alt=\"gajidori\" class=\"gajidori\"></a>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                </header>\r\n");
      out.write("	                <nav>\r\n");
      out.write("	                    <ul>\r\n");
      out.write("	                        <li><a id=\"li_link\" href=\"BoardList.jsp\" style=\"text-decoration: none;\">자유게시판</a></li>\r\n");
      out.write("	                        <li><a id=\"li_link\" href=\"reviewList.jsp\" style=\"text-decoration: none;\">리뷰게시판</a></li>\r\n");
      out.write("	                        <li><a id=\"li_link\" href=\"QnAList.jsp\" style=\"text-decoration: none;\">문의게시판</a></li>\r\n");
      out.write("	                        <li><a id=\"li_link\" href=\"productRetrieve.jsp\" style=\"text-decoration: none;\">마이페이지</a></li>\r\n");
      out.write("	                    </ul>\r\n");
      out.write("	                </nav>\r\n");
      out.write("		        </div>\r\n");
      out.write("		");

			String reviewNoValue = (String) request.getParameter("REVIEW_NO");
			int reviewNo = Integer.parseInt(reviewNoValue);
			ReviewDAO reviewDao = new ReviewDAO();
			Review review = reviewDao.getReviewNo(reviewNo);
		
      out.write("\r\n");
      out.write("			<div class=\"mainform\">\r\n");
      out.write("				<p class=\"maintable\">\r\n");
      out.write("					<br>번호 : ");
      out.print(review.getREVIEW_NO());
      out.write("<br>\r\n");
      out.write("					제목 : ");
      out.print(review.getREVIEW_TITLE());
      out.write("<br>\r\n");
      out.write("					내용 : ");
      out.print(review.getREVIEW_TEXT());
      out.write("<br>\r\n");
      out.write("					사용자ID : ");
      out.print(review.getACCOUNT_ID());
      out.write("<br>\r\n");
      out.write("					작성시간 : ");
      out.print(review.getREVIEW_TIME());
      out.write("\r\n");
      out.write("				</p>\r\n");
      out.write("				<div class=\"buttons\">\r\n");
      out.write("						<button class=\"btn1\" id=\"listButton\"><a id=\"aTag\" href =\"reviewList.jsp\">목록</a></button>\r\n");
      out.write("						<button class=\"btn1\" id=\"updateButton\" onclick=\"location.href='reviewUpdate.jsp?REVIEW_No=");
      out.print(reviewNo);
      out.write("'\">수정</button>\r\n");
      out.write("						<form action=\"reviewDelete.jsp?REVIEW_No=");
      out.print(reviewNo);
      out.write("\" method=\"post\">\r\n");
      out.write("							<button class=\"btn1\" type=\"submit\" id=\"deleteButton\" onclick=\"Location.href='reviewDelete.jsp?REVIEW_NO=");
      out.print(reviewNo);
      out.write("'\">삭제</button>\r\n");
      out.write("						</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"returnMain\">\r\n");
      out.write("	        	<a id=\"aTag\" href=\"reviewList.jsp\">\r\n");
      out.write("	       			<img src=\"./img/goToMain.jpg\" width=\"120px\">\r\n");
      out.write("	       		</a>\r\n");
      out.write("       		</div>\r\n");
      out.write("			<footer>\r\n");
      out.write("			<p>회사소개 | 인재채용 | 제휴제안 | 이용약관 | 개인정보처리방침 | 청소년보호정책 | 고객센터 | GAZI Corp.</p>\r\n");
      out.write("			</footer>\r\n");
      out.write("	        </div>\r\n");
      out.write("	    </div>\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
